spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    kubernetes:
      enabled: false
      config:
        enabled: false
  zipkin:
    enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 4

    url: jdbc:postgresql://localhost:5432/shop?currentSchema=sh
    driver-class-name: org.postgresql.Driver
    username: adm
    password: adm

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: shop

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_schema: sh
        criteria:
          literal_handling_mode: BIND
    hibernate:
      naming:
        physical-strategy: ru.shop.Utils.ShopNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect

  liquibase:
    enabled: false

server:
  port: 8080

##
# Properties for cache time - TimeUnit.MILLISECONDS
##
cache-properties:
  time: 600000
  maximumSize: 10000
  defaultMaximumSize: 10000